-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2Dfixp is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    in_V_ce0 : OUT STD_LOGIC;
    in_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    out_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_V_ce0 : OUT STD_LOGIC;
    out_V_we0 : OUT STD_LOGIC;
    out_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    kernel_V_ce0 : OUT STD_LOGIC;
    kernel_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of conv2Dfixp is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2Dfixp,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.634000,HLS_SYN_LAT=36905,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=134,HLS_SYN_LUT=326}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_cast_fu_141_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_cast_reg_454 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_1_fu_151_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_462 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_181_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_reg_467 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond1_fu_145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_cast_fu_187_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_cast_reg_472 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal j_1_fu_197_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_1_reg_480 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_V_addr_reg_485 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond2_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_1_fu_227_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_1_reg_493 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp1_fu_233_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp1_reg_498 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond3_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_cast_fu_291_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_7_cast_reg_503 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_3_fu_311_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_3_reg_508 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp3_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_reg_513 : STD_LOGIC_VECTOR (0 downto 0);
    signal n_1_fu_329_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal n_1_reg_521 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp2_fu_335_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp2_reg_526 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_reg_531 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal in_V_load_reg_545 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal kernel_V_load_reg_550 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_s_reg_555 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_reg_95 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_reg_106 : STD_LOGIC_VECTOR (4 downto 0);
    signal m_reg_117 : STD_LOGIC_VECTOR (1 downto 0);
    signal n_reg_129 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_5_fu_216_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_fu_399_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_fu_417_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_shl_fu_157_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl9_fu_169_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_cast_fu_165_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl9_cast_fu_177_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_cast_fu_203_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_207_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_cast_fu_212_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp1_cast_fu_245_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ii_fu_248_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_253_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_shl1_fu_277_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_cast_fu_273_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_285_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mm_fu_239_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_shl2_fu_299_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl2_cast_fu_307_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_9_cast5_fu_295_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_cast_fu_347_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal jj_fu_350_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev4_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_cast_fu_386_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_9_fu_390_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_15_cast_fu_395_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal nn_fu_341_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_cast_fu_404_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_10_fu_408_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_18_cast_fu_413_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_445_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_445_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);

    component conv2Dfixp_mac_mubkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (27 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;



begin
    conv2Dfixp_mac_mubkb_U1 : component conv2Dfixp_mac_mubkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        din0 => in_V_load_reg_545,
        din1 => kernel_V_load_reg_550,
        din2 => grp_fu_445_p2,
        dout => grp_fu_445_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_reg_95_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond2_fu_191_p2 = ap_const_lv1_1))) then 
                i_reg_95 <= i_1_reg_462;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_95 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    j_reg_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond3_fu_221_p2 = ap_const_lv1_1))) then 
                j_reg_106 <= j_1_reg_480;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond1_fu_145_p2 = ap_const_lv1_0))) then 
                j_reg_106 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    m_reg_117_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (exitcond_fu_323_p2 = ap_const_lv1_1))) then 
                m_reg_117 <= m_1_reg_493;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_0 = exitcond2_fu_191_p2))) then 
                m_reg_117 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    n_reg_129_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                n_reg_129 <= n_1_reg_521;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                n_reg_129 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_1_reg_462 <= i_1_fu_151_p2;
                    i_cast_reg_454(4 downto 0) <= i_cast_fu_141_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                in_V_load_reg_545 <= in_V_q0;
                kernel_V_load_reg_550 <= kernel_V_q0;
                p_Val2_s_reg_555 <= out_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                j_1_reg_480 <= j_1_fu_197_p2;
                    j_cast_reg_472(4 downto 0) <= j_cast_fu_187_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                m_1_reg_493 <= m_1_fu_227_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                n_1_reg_521 <= n_1_fu_329_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                or_cond2_reg_531 <= or_cond2_fu_381_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_0 = exitcond2_fu_191_p2))) then
                out_V_addr_reg_485 <= tmp_5_fu_216_p1(10 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_0 = exitcond3_fu_221_p2))) then
                tmp1_reg_498 <= tmp1_fu_233_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_0 = exitcond_fu_323_p2))) then
                tmp2_reg_526 <= tmp2_fu_335_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tmp3_reg_513 <= tmp3_fu_317_p2;
                tmp_3_reg_508 <= tmp_3_fu_311_p2;
                tmp_7_cast_reg_503 <= tmp_7_cast_fu_291_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond1_fu_145_p2 = ap_const_lv1_0))) then
                    tmp_1_reg_467(10 downto 2) <= tmp_1_fu_181_p2(10 downto 2);
            end if;
        end if;
    end process;
    i_cast_reg_454(5) <= '0';
    tmp_1_reg_467(1 downto 0) <= "00";
    j_cast_reg_472(5) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond1_fu_145_p2, ap_CS_fsm_state3, exitcond2_fu_191_p2, ap_CS_fsm_state4, exitcond3_fu_221_p2, ap_CS_fsm_state6, exitcond_fu_323_p2, or_cond2_fu_381_p2, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond1_fu_145_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond2_fu_191_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond3_fu_221_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (exitcond_fu_323_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_0 = or_cond2_fu_381_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_CS_fsm_state2, exitcond1_fu_145_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond1_fu_145_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond1_fu_145_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond1_fu_145_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_fu_145_p2 <= "1" when (i_reg_95 = ap_const_lv5_1C) else "0";
    exitcond2_fu_191_p2 <= "1" when (j_reg_106 = ap_const_lv5_1C) else "0";
    exitcond3_fu_221_p2 <= "1" when (m_reg_117 = ap_const_lv2_3) else "0";
    exitcond_fu_323_p2 <= "1" when (n_reg_129 = ap_const_lv2_3) else "0";
    grp_fu_445_p2 <= (p_Val2_s_reg_555 & ap_const_lv12_0);
    i_1_fu_151_p2 <= std_logic_vector(unsigned(i_reg_95) + unsigned(ap_const_lv5_1));
    i_cast_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_95),6));
    ii_fu_248_p2 <= std_logic_vector(unsigned(i_cast_reg_454) + unsigned(tmp1_cast_fu_245_p1));
    in_V_address0 <= tmp_s_fu_399_p1(10 - 1 downto 0);

    in_V_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            in_V_ce0 <= ap_const_logic_1;
        else 
            in_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_197_p2 <= std_logic_vector(unsigned(j_reg_106) + unsigned(ap_const_lv5_1));
    j_cast_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_106),6));
    jj_fu_350_p2 <= std_logic_vector(signed(tmp2_cast_fu_347_p1) + signed(j_cast_reg_472));
    kernel_V_address0 <= tmp_11_fu_417_p1(4 - 1 downto 0);

    kernel_V_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            kernel_V_ce0 <= ap_const_logic_1;
        else 
            kernel_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m_1_fu_227_p2 <= std_logic_vector(unsigned(m_reg_117) + unsigned(ap_const_lv2_1));
    mm_fu_239_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(m_reg_117));
    n_1_fu_329_p2 <= std_logic_vector(unsigned(n_reg_129) + unsigned(ap_const_lv2_1));
    nn_fu_341_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(n_reg_129));
    or_cond2_fu_381_p2 <= (tmp4_fu_375_p2 and tmp3_reg_513);
    out_V_address0 <= out_V_addr_reg_485;

    out_V_ce0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            out_V_ce0 <= ap_const_logic_1;
        else 
            out_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_V_d0 <= grp_fu_445_p3(27 downto 12);

    out_V_we0_assign_proc : process(or_cond2_reg_531, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (or_cond2_reg_531 = ap_const_lv1_1))) then 
            out_V_we0 <= ap_const_logic_1;
        else 
            out_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_fu_277_p3 <= (ii_fu_248_p2 & ap_const_lv2_0);
    p_shl2_cast_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_fu_299_p3),5));
    p_shl2_fu_299_p3 <= (mm_fu_239_p2 & ap_const_lv2_0);
    p_shl9_cast_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl9_fu_169_p3),11));
    p_shl9_fu_169_p3 <= (i_reg_95 & ap_const_lv2_0);
    p_shl_cast_fu_165_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_157_p3),11));
    p_shl_fu_157_p3 <= (i_reg_95 & ap_const_lv5_0);
    rev4_fu_363_p2 <= (tmp_6_fu_355_p3 xor ap_const_lv1_1);
    rev_fu_261_p2 <= (tmp_fu_253_p3 xor ap_const_lv1_1);
        tmp1_cast_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp1_reg_498),6));

    tmp1_fu_233_p2 <= std_logic_vector(unsigned(m_reg_117) + unsigned(ap_const_lv2_3));
        tmp2_cast_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp2_reg_526),6));

    tmp2_fu_335_p2 <= std_logic_vector(unsigned(n_reg_129) + unsigned(ap_const_lv2_3));
    tmp3_fu_317_p2 <= (tmp_2_fu_267_p2 and rev_fu_261_p2);
    tmp4_fu_375_p2 <= (tmp_8_fu_369_p2 and rev4_fu_363_p2);
    tmp_10_fu_408_p2 <= std_logic_vector(unsigned(tmp_3_reg_508) + unsigned(tmp_17_cast_fu_404_p1));
    tmp_11_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_cast_fu_413_p1),64));
    tmp_14_cast_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(jj_fu_350_p2),9));
        tmp_15_cast_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_390_p2),32));

    tmp_17_cast_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(nn_fu_341_p2),5));
        tmp_18_cast_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_408_p2),32));

    tmp_1_fu_181_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_165_p1) - unsigned(p_shl9_cast_fu_177_p1));
    tmp_2_fu_267_p2 <= "1" when (signed(ii_fu_248_p2) < signed(ap_const_lv6_1C)) else "0";
    tmp_3_cast_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_106),11));
    tmp_3_fu_311_p2 <= std_logic_vector(unsigned(p_shl2_cast_fu_307_p1) - unsigned(tmp_9_cast5_fu_295_p1));
        tmp_4_cast_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_207_p2),32));

    tmp_4_fu_207_p2 <= std_logic_vector(unsigned(tmp_1_reg_467) + unsigned(tmp_3_cast_fu_203_p1));
    tmp_5_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_cast_fu_212_p1),64));
        tmp_6_cast_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ii_fu_248_p2),8));

    tmp_6_fu_355_p3 <= jj_fu_350_p2(5 downto 5);
        tmp_7_cast_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_285_p2),9));

    tmp_7_fu_285_p2 <= std_logic_vector(unsigned(p_shl1_fu_277_p3) - unsigned(tmp_6_cast_fu_273_p1));
    tmp_8_fu_369_p2 <= "1" when (signed(jj_fu_350_p2) < signed(ap_const_lv6_1C)) else "0";
    tmp_9_cast5_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mm_fu_239_p2),5));
    tmp_9_fu_390_p2 <= std_logic_vector(signed(tmp_7_cast_reg_503) + signed(tmp_14_cast_fu_386_p1));
    tmp_fu_253_p3 <= ii_fu_248_p2(5 downto 5);
    tmp_s_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_cast_fu_395_p1),64));
end behav;
