// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_conv2Dfixp (
ap_fixed<16, 4, (ap_q_mode) 5, (ap_o_mode)3, 0> in[784],
ap_fixed<16, 4, (ap_q_mode) 5, (ap_o_mode)3, 0> out[784],
ap_fixed<16, 4, (ap_q_mode) 5, (ap_o_mode)3, 0> kernel[9]);
